---
name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythonVersion: [10]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.${{ matrix.pythonVersion }}"
      - name: Run black
        uses: psf/black@stable
      - name: Run isort
        uses: isort/isort-action@v1
      - name: Run flake8
        uses: py-actions/flake8@v2
      - name: Run ruff
        uses: chartboost/ruff-action@v1
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.7.1"
      - name: Check project evaluation steps
        run: |
          poetry install
          poetry run pre-commit install
          poetry run pre-commit run --all-files
          poetry run python train.py --no-mlflow
          poetry run python infer.py -o - | head
